dist: trusty
jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t cattlechain_tp .
      - docker images
      - docker tag cattlechain_tp $DOCKER_USERNAME/cattlechain_tp
      - docker push $DOCKER_USERNAME/cattlechain_tp